import React, { useState, useEffect, useCallback } from 'react';
import { PageContainer } from '@ant-design/pro-components';
import { ProTable } from '@ant-design/pro-components';
import type { ProColumns } from '@ant-design/pro-components';
import { Button, Popconfirm } from 'antd';
import { useModel } from 'umi';
import { useLocation } from 'react-router-dom';
import type { DiplomaInfo } from '@/models/diploma';
import AddDiplomaForm from './AddDiplomaForm';

const DiplomaInfoPage: React.FC = () => {
  const { diplomaInfos, removeDiploma } = useModel('diploma'); // Giả sử có hàm xóa văn bằng
  const location = useLocation();
  const params = new URLSearchParams(location.search);
  const decision = params.get('decision'); // Lấy số quyết định từ URL
  const [filteredDiplomaInfos, setFilteredDiplomaInfos] = useState<DiplomaInfo[]>([]);

  useEffect(() => {
    setFilteredDiplomaInfos(diplomaInfos.filter(info => !info.autoGenerated));
  }, [diplomaInfos]);

  const handleSuccess = useCallback(() => {
    setFilteredDiplomaInfos([...diplomaInfos.filter(info => !info.autoGenerated)]);
  }, [diplomaInfos]);

  const handleDelete = (id: string) => {
    removeDiploma(id); // Giả sử đây là hàm xóa từ model
    setFilteredDiplomaInfos(prev => prev.filter(item => item.id !== id));
  };

  const columns: ProColumns<DiplomaInfo>[] = [
    { title: 'Số vào sổ', dataIndex: 'bookNumber', width: 100 },
    { title: 'Số hiệu văn bằng', dataIndex: 'diplomaNumber', width: 150 },
    { title: 'Mã sinh viên', dataIndex: 'studentId', width: 120 },
    { title: 'Họ tên', dataIndex: 'fullName', width: 200 },
    {
      title: 'Xem thêm',
      dataIndex: 'actions',
      width: 100,
      render: (_, record) => (
        <Button type="link" onClick={() => console.log('Chi tiết:', record)}>Chi tiết</Button>
      ),
    },
    {
      title: 'Xóa',
      dataIndex: 'delete',
      width: 80,
      render: (_, record) => (
        <Popconfirm
          title="Bạn có chắc chắn muốn xóa?"
          onConfirm={() => handleDelete(record.id)}
          okText="Xóa"
          cancelText="Hủy"
        >
          <Button type="link" danger>Xóa</Button>
        </Popconfirm>
      ),
    },
  ];

  return (
    <PageContainer header={{ title: `Thông tin văn bằng - QĐ: ${decision || 'Không xác định'}` }}>
      {/* Truyền số quyết định vào AddDiplomaForm */}
      <AddDiplomaForm onSuccess={handleSuccess} decision={decision} />
      <ProTable<DiplomaInfo>
        rowKey="id"
        search={false}
        columns={columns}
        dataSource={filteredDiplomaInfos}
        pagination={{ pageSize: 10, showSizeChanger: true, showQuickJumper: true }}
      />
    </PageContainer>
  );
};

export default DiplomaInfoPage;
