import React, { useState, useCallback } from 'react';
import { PageContainer, ProTable } from '@ant-design/pro-components';
import type { ProColumns } from '@ant-design/pro-components';
import { Button, Popconfirm, Modal, Descriptions } from 'antd';
import { useModel } from 'umi';
import { useLocation } from 'react-router-dom';
import type { DiplomaInfo } from '@/models/diploma';
import AddDiplomaForm from './AddDiplomaForm';

const DiplomaInfoPage: React.FC = () => {
	const { diplomaInfos, removeDiploma } = useModel('diploma');
	const location = useLocation();
	const params = new URLSearchParams(location.search);
	const decision = params.get('decision');

	const [filteredDiplomaInfos, setFilteredDiplomaInfos] = useState<DiplomaInfo[]>([]);
	const [selectedDiploma, setSelectedDiploma] = useState<DiplomaInfo | null>(null);
	const [modalVisible, setModalVisible] = useState(false);

	const handleSuccess = useCallback(() => {
		setFilteredDiplomaInfos(diplomaInfos.filter((info) => !info.autoGenerated));
	}, [diplomaInfos]);

	const handleDelete = (id: string) => {
		removeDiploma(id);
		setFilteredDiplomaInfos((prev) => prev.filter((item) => item.id !== id));
	};

	const handleViewDetails = (record: DiplomaInfo) => {
		setSelectedDiploma(record);
		setModalVisible(true);
	};

	const columns: ProColumns<DiplomaInfo>[] = [
		{ title: 'Số vào sổ', dataIndex: 'bookNumber', width: 100 },
		{ title: 'Số hiệu văn bằng', dataIndex: 'diplomaNumber', width: 150 },
		{ title: 'Mã sinh viên', dataIndex: 'studentId', width: 120 },
		{ title: 'Họ tên', dataIndex: 'fullName', width: 200 },
		{
			title: 'Xem thêm',
			dataIndex: 'actions',
			width: 100,
			render: (_, record) => (
				<Button type='link' onClick={() => handleViewDetails(record)}>
					Chi tiết
				</Button>
			),
		},
		{
			title: 'Xóa',
			dataIndex: 'delete',
			width: 80,
			render: (_, record) => (
				<Popconfirm
					title='Bạn có chắc chắn muốn xóa?'
					onConfirm={() => handleDelete(record.id)}
					okText='Xóa'
					cancelText='Hủy'
				>
					<Button type='link' danger>
						Xóa
					</Button>
				</Popconfirm>
			),
		},
	];

	return (
		<PageContainer header={{ title: `Thông tin văn bằng - QĐ: ${decision || 'Không xác định'}` }}>
			<AddDiplomaForm onSuccess={handleSuccess} decision={decision} />
			<ProTable<DiplomaInfo>
				rowKey='id'
				search={false}
				columns={columns}
				dataSource={filteredDiplomaInfos}
				pagination={{ pageSize: 10, showSizeChanger: true, showQuickJumper: true }}
			/>
			<Modal title='Chi tiết văn bằng' visible={modalVisible} onCancel={() => setModalVisible(false)} footer={null}>
				{selectedDiploma && (
					<Descriptions column={1} bordered>
						<Descriptions.Item label='Số vào sổ'>{selectedDiploma.bookNumber}</Descriptions.Item>
						<Descriptions.Item label='Số hiệu văn bằng'>{selectedDiploma.diplomaNumber}</Descriptions.Item>
						<Descriptions.Item label='Mã sinh viên'>{selectedDiploma.studentId}</Descriptions.Item>
						<Descriptions.Item label='Họ tên'>{selectedDiploma.fullName}</Descriptions.Item>
						<Descriptions.Item label='Ngày cấp'>{selectedDiploma.issueDate}</Descriptions.Item>
						<Descriptions.Item label='Xếp loại'>{selectedDiploma.grade}</Descriptions.Item>
						<Descriptions.Item label='Ngành học'>{selectedDiploma.major}</Descriptions.Item>
					</Descriptions>
				)}
			</Modal>
		</PageContainer>
	);
};

export default DiplomaInfoPage;
