import { useState, useCallback, useEffect } from 'react';
import {
	getDiplomaBooks,
	createDiplomaBook as createDiplomaBookService,
	getGraduationDecisions,
	createGraduationDecision as createGraduationDecisionService,
	getDiplomaFormFields,
	createDiplomaFormField as createDiplomaFormFieldService,
	updateDiplomaFormField as updateDiplomaFormFieldService,
	deleteDiplomaFormField as deleteDiplomaFormFieldService,
	getDiplomaInfos,
	createDiplomaInfo as createDiplomaInfoService,
	searchDiplomaInfo as searchDiplomaInfoService,
	deleteDiplomaInfo as deleteDiplomaInfoService,
} from '@/services/diploma';

export type DataType = 'String' | 'Number' | 'Date';

export interface DiplomaFormField {
	id: string;
	name: string;
	dataType: DataType;
	required: boolean;
	order: number;
}

export interface DiplomaBook {
	id: string;
	year: number;
	currentNumber: number;
	createdAt: string;
	updatedAt: string;
}

export interface GraduationDecision {
	id: string;
	number: string;
	issueDate: string;
	summary: string;
	diplomaBookId: string;
	createdAt: string;
	updatedAt: string;
}

export interface DiplomaInfo {
	id: string;
	studentId: string;
	fullName: string;
	ethnicity: string;
	placeOfBirth: string;
	admissionDate: string;
	averageRank: number;
	graduationDecisionId: string;
	customFields: Record<string, any>;
	createdAt: string;
	updatedAt: string;
	bookNumber: string;
	diplomaNumber: string;
	autoGenerated?: boolean;
}

interface ApiResponse<T> {
	data: T;
	status: number;
	message?: string;
}

export default function useDiplomaModel() {
	const [diplomaBooks, setDiplomaBooks] = useState<DiplomaBook[]>([]);
	const [graduationDecisions, setGraduationDecisions] = useState<GraduationDecision[]>([]);
	const [diplomaFormFields, setDiplomaFormFields] = useState<DiplomaFormField[]>([]);
	const [diplomaInfos, setDiplomaInfos] = useState<DiplomaInfo[]>([]);

	// 🛠 Tải dữ liệu ban đầu
	useEffect(() => {
		const loadData = async () => {
			try {
				const [booksRes, decisionsRes, fieldsRes, infosRes] = await Promise.all([
					getDiplomaBooks(),
					getGraduationDecisions(),
					getDiplomaFormFields(),
					getDiplomaInfos(),
				]);

				setDiplomaBooks(booksRes.data || []);
				setGraduationDecisions(decisionsRes.data || []);
				setDiplomaFormFields(fieldsRes.data || []);
				setDiplomaInfos(infosRes.data || []);
			} catch (error) {
				console.error('⚠️ Lỗi khi tải dữ liệu:', error);
			}
		};

		loadData();
	}, []);

	// 📌 Thêm sổ văn bằng
	const createDiplomaBook = useCallback(async (year: number) => {
		try {
			const response: ApiResponse<DiplomaBook> = await createDiplomaBookService(year);
			if (response.data) {
				setDiplomaBooks((prev) => [...prev, response.data]);
				return response.data;
			}
			throw new Error(response.message || 'Không thể tạo sổ văn bằng');
		} catch (error) {
			console.error('⚠️ Lỗi khi tạo sổ văn bằng:', error);
		}
	}, []);

	// 📌 Thêm quyết định tốt nghiệp
	const createGraduationDecision = useCallback(
		async (decision: Omit<GraduationDecision, 'id' | 'createdAt' | 'updatedAt'>) => {
			try {
				const response: ApiResponse<GraduationDecision> = await createGraduationDecisionService(decision);
				if (response.data) {
					setGraduationDecisions((prev) => [...prev, response.data]);
					return response.data;
				}
				throw new Error(response.message || 'Không thể tạo quyết định tốt nghiệp');
			} catch (error) {
				console.error('⚠️ Lỗi khi tạo quyết định tốt nghiệp:', error);
			}
		},
		[],
	);

	// 📌 Quản lý trường thông tin văn bằng
	const createDiplomaFormField = useCallback(async (field: Omit<DiplomaFormField, 'id'>) => {
		try {
			const response: ApiResponse<DiplomaFormField> = await createDiplomaFormFieldService(field);
			if (response.data) {
				setDiplomaFormFields((prev) => [...prev, response.data]);
				return response.data;
			}
			throw new Error(response.message || 'Không thể tạo trường thông tin');
		} catch (error) {
			console.error('⚠️ Lỗi khi tạo trường thông tin:', error);
		}
	}, []);

	const updateDiplomaFormField = useCallback(async (field: DiplomaFormField) => {
		try {
			const response: ApiResponse<DiplomaFormField> = await updateDiplomaFormFieldService(field);
			if (response.data) {
				setDiplomaFormFields((prev) => prev.map((item) => (item.id === field.id ? response.data : item)));
				return response.data;
			}
			throw new Error(response.message || 'Không thể cập nhật trường thông tin');
		} catch (error) {
			console.error('⚠️ Lỗi khi cập nhật trường thông tin:', error);
		}
	}, []);

	const deleteDiplomaFormField = useCallback(async (id: string) => {
		try {
			await deleteDiplomaFormFieldService(id);
			setDiplomaFormFields((prev) => prev.filter((item) => item.id !== id));
		} catch (error) {
			console.error('⚠️ Lỗi khi xóa trường thông tin:', error);
		}
	}, []);

	// 📌 Thêm và tìm kiếm văn bằng
	const createDiplomaInfo = useCallback(async (data: Omit<DiplomaInfo, 'id' | 'createdAt' | 'updatedAt'>) => {
		try {
			const response: ApiResponse<DiplomaInfo> = await createDiplomaInfoService(data);
			if (response.data) {
				setDiplomaInfos((prev) => [...prev, response.data]);
				return response.data;
			}
			throw new Error(response.message || 'Không thể tạo văn bằng');
		} catch (error) {
			console.error('⚠️ Lỗi khi tạo văn bằng:', error);
		}
	}, []);

	const searchDiplomaInfo = useCallback(async (query: Partial<DiplomaInfo>) => {
		try {
			const response: ApiResponse<DiplomaInfo[]> = await searchDiplomaInfoService(query);
			setDiplomaInfos(response.data || []);
		} catch (error) {
			console.error('⚠️ Lỗi khi tìm kiếm văn bằng:', error);
		}
	}, []);

	// 📌 Xóa văn bằng
	const removeDiploma = useCallback(async (id: string) => {
		try {
			await deleteDiplomaInfoService(id);
			setDiplomaInfos((prev) => prev.filter((item) => item.id !== id));
		} catch (error) {
			console.error('⚠️ Lỗi khi xóa văn bằng:', error);
		}
	}, []);

	return {
		diplomaBooks,
		graduationDecisions,
		diplomaFormFields,
		diplomaInfos,
		createDiplomaBook,
		createGraduationDecision,
		createDiplomaFormField,
		updateDiplomaFormField,
		deleteDiplomaFormField,
		createDiplomaInfo,
		searchDiplomaInfo,
		removeDiploma,
	};
}
